sudo: required
services: 
  - docker 

before_install: 
  - docker build -t marionascitini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marionascitini/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "my-elastic"
  env: "My-elastic-env"
  bucket_name: "elasticbeanstalk-us-east-1-740124185335"
  bucket_path: "my-elastic"
  on:
    branch: main 
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
