sudo: required
services: 
  - docker 

before_install: 
  - docker build -t marionascitini/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marionascitini/docker-react npm run test
